### ISSUE TITLE
Is it possible to use diamond or mmseqs as blast engine when running BLASTER?

### ISSUE THREAD

**Issue by xiekunwhy** [urgi-anagen/TE_finder#1]
Hi,

As ncbi blast as well as WU-BLAST is too slow, would you please make some modification to accept diamond (https://github.com/bbuchfink/diamond) or mmseqs2 (https://github.com/soedinglab/MMseqs2) as blast engine?

Best,
Kun

**Comment by hquesneville** [comment]
Dear Kun,

Thank you for this question and your interest in Blaster. Diamond and MMseq2 are well suited for protein search. I do not see really an added value to use Blaster in this context. For DNA search we tested Minimap2 which works well. It is quick but less sensitive as expected. I do not see today the added value to implement Minimap2 in Blaster, but perhaps you can explain me the usage you see ?

However keep in mind that blast is multithreaded and you can use it with several threads in Blaster by passing the correct parameter. By default Blaster run Blast with 1 thread.

Best regards,

Hadi
----------------------------------------------------------------------
Hadi Quesneville
Directeur de recherche / Research director
Administrateur des Données Algorithmes et Codes de la recherche (ADAC) / Chief Data Officer

***@***.******@***.***>
Unité de Recherches en Génomique-Info (UR INRAE 1164),
INRAE, Centre de recherche de Versailles, bat.18
RD10, Route de Saint Cyr
78026 Versailles Cedex, FRANCE

Tél: +33 1 30 83 30 08
mob: +33 6 45 46 78 86
Fax: +33 1 30 83 38 99
http://urgi.versailles.inrae.fr
Twitter: @hquesneville
LinkedIn : hquesneville


***@***.***

Le 28 avr. 2022 à 20:18, xiekunwhy ***@***.******@***.***>> a écrit :



Hi,

As ncbi blast as well as WU-BLAST is too slow, would you please make some modification to accept diamond (https://github.com/bbuchfink/diamond) or mmseqs2 (https://github.com/soedinglab/MMseqs2) as blast engine?

Best,
Kun

**Comment by xiekunwhy** [comment]
Dear Hadi,

MMseq2 can do DNA search, I am trying to prepare \*.align file using mmseq2 results, and skip blaster step.

Best regards,
Kun
