### ISSUE TITLE
We still need to annotate duster results?

### ISSUE THREAD

**Issue by xiekunwhy** [urgi-anagen/TE_finder#2]
Hi,

I can't find any relationship infomation between DUSTER results and TE library sequences using test data, so we still need to annoate Duster results?

Or is there an easy way to know TE classes in DUSTER results?

Best,
Kun

**Comment by hquesneville** [comment]
Dear Kun,

DUSTER is made to detect very old TE which are difficult to detect by other means. They are often so old and degenerated that it is difficult to see the type of TE the sequence belongs to. Consequently it is not able to determine the class.

 Best,

Hadi
----------------------------------------------------------------------
Hadi Quesneville
Directeur de recherche / Research director
Administrateur des Données Algorithmes et Codes de la recherche (ADAC) / Chief Data Officer

***@***.******@***.***>
Unité de Recherches en Génomique-Info (UR INRAE 1164),
INRAE, Centre de recherche de Versailles, bat.18
RD10, Route de Saint Cyr
78026 Versailles Cedex, FRANCE

Tél: +33 1 30 83 30 08
mob: +33 6 45 46 78 86
Fax: +33 1 30 83 38 99
http://urgi.versailles.inrae.fr
Twitter: @hquesneville
LinkedIn : hquesneville


***@***.***

Le 7 juil. 2022 à 09:10, xiekunwhy ***@***.******@***.***>> a écrit :



Hi,

I can't find any relationship infomation between DUSTER results and TE library sequences using test data, so we still need to annoate Duster results?

Or is there an easy way to know TE classes of DUSTER results?

Best,
Kun

**Comment by xiekunwhy** [comment]
Dear Hadi,

The not so old TEs are also included in duster results, right? So I need to annotate the duster results using some other tools like censor or repeatmasker to get the class information of those not so old TEs, I will do that.

Best,
Kun
