### ISSUE TITLE
compilation fails

### ISSUE THREAD

**Issue by EtienneBucher** [urgi-anagen/TE_finder#4]
When I try to compile TE_finder I get the following error: 

/home/centos/TE_finder/src/BLRlib/testfiles/Test_BLRMatchMap.cpp:21:49: error: no 'void Test_BLRMatchMap::test_clean_conflicts()' member function declared in class 'Test_BLRMatchMap'
 void Test_BLRMatchMap::test_clean_conflicts(void){
                                                 ^
make[2]: *** [src/BLRlib/testfiles/CMakeFiles/test_BLR.dir/Test_BLRMatchMap.cpp.o] Error 1
make[1]: *** [src/BLRlib/testfiles/CMakeFiles/test_BLR.dir/all] Error 2
make: *** [all] Error 2

I tested it with CentOS and Ubuntu Linux

**Comment by hquesneville** [comment]
Thank you for the feedback ! 

I cleaned the master branch that was indeed in an unstable code state. Now it should be ok for the compilation. I made also a release package that you can download as a zip file if more convenient.

Let me know if there is still a problem.

**Comment by EtienneBucher** [comment]
Perfect, it works now, thank you very much!
